name: Docs

on:
    push:
        branches:
        -   main

jobs:
    latest:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:

        -   name: Checkout
            uses: actions/checkout@v3
            with:
                persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

        -   name: Setup
            uses: conda-incubator/setup-miniconda@v2
            with:
                auto-update-conda: true
                activate-environment: docs
                environment-file: docs/environment.yml
                python-version: '3.10'

        -   name: Build
            shell: bash -l {0}
            run: |
                cd docs/
                make dirhtml

        -   name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
                name: dirhtml
                path: docs/_build/dirhtml/

        # Deploy to S3
        -   name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1.6.1
            with:
                aws-region: ${{secrets.AWS_REGION}}
                role-to-assume: ${{ secrets.AWS_OIDC_RUNNER_ROLE }}

        -   name: Copy redirect file
            run: aws s3 cp --quiet ./docs/_build/dirhtml/_static/redirect.html s3://docs.pyscript.net/index.html

        -   name: Delete latest directory
            run: aws s3 rm --recursive s3://docs.pyscript.net/latest/

        -   name: Sync to S3
            run: aws s3 sync --quiet ./docs/_build/dirhtml/ s3://docs.pyscript.net/latest/

        -   name: Set commit status to error
            uses: Sibz/github-status-action@v1
            with:
                context: Review documentation
                description: See details link for the build result.
                state: success
                target_url: https://docs.pyscript.net/latest/
